[package]
name = "distributed-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
rand = "0.9.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls","chrono"] }
